### ISSUE TITLE
Include this module in main policy tree?

### ISSUE THREAD

**Issue by jsegitz** [containers/container-selinux#186]
I've been wondering why this module is developed in it's on repository while >400 other contrib modules are part of the main (Fedora) policy repository.

I've read old issue to get a clue (mainly https://github.com/containers/container-selinux/issues/113, but that's primarily about refpolicy). While merging this into the main policy tree I've come across some neverallow failures when including the module directly. Maybe that's the reason. I have a 350 line patch that adds some interfaces to allow the module to compile when neverallow rules are checked.

Keeping this as a separate module can cause issues like https://github.com/containers/container-selinux/issues/164 because the packaging needs to make sure that the right order of updating is ensured if there are changes on either side that are incompatible with previous versions. This and also the general need for containers on many systems would be a reason to think about integrating this into the main policy.

Is there something I'm missing? Otherwise I would open a PR to get the needed interfaces into the main policy as a first step

**Comment by rhatdan** [comment]
It is a mere matter of effort.  If someone wants to merge this into RefPolicy I am fine with that.  BUT Fedora policy and RefPolicy have drifted hugely over the last 15-20 year so merging them is impossible.  Since containers-selinux is mainly used on Fedora and it's descendants, container-selinux will remain based on it.  

If you want to open PRs to make it easier to merge, I am very willing to accept them.

**Comment by jsegitz** [comment]
I want to merge this into the Fedora policy, not RefPolicy. For RefPolicy I agree with you that this would be quite painful.

**Comment by rhatdan** [comment]
The problem with merging this into fedora-policy is it ties the releases together.  While container policy was being developed it changed at a much higher rate then standard fedora-policy so keeping it separate made sense.  Now it has stabilized, so it might make more sense.

I am not against merging it, but on the other hand, the goal with selinux-policy was always to get packagers to package their own policy since they would be subject matter expert versus the selinux-policy maintainers.

@wrabcak @zpytela WDYT

**Comment by zpytela** [comment]
Certainly there are pros and cons as always and in each model there will be issues like the one mentioned above from time to time.

What I see as the biggest benefit of the separation is not higher rate of changes, but rather synchronization of changes in the code with changes in policy.

It could even be beneficial to separate the container module from selinux-policy so there is just one-way dependency, but this would require a lot of effort and I don't think it pays off.

Having said that, currently my standpoint is that I am not for the suggested merge nor for any other change unless there were additional arguments or business driver for such a change. It could be e. g. frequent modifications in kernel or substantial changes in policy which is not planned though now.

Also note container is not the only independent module, just probably the most visible one.

**Comment by rhatdan** [comment]
I agree, and we have been working well together for almost 10 years, so don't break what is not broken.

**Comment by jsegitz** [comment]
This module is needed to build the Fedora policy:
https://src.fedoraproject.org/rpms/selinux-policy/blob/rawhide/f/selinux-policy.spec#_58

So while I see some of your points I don't agree with the conclusion. If it's needed for building it should be included by default.

**Comment by rhatdan** [comment]
This is an issue with interface files. selinux-policy is using some interface files to access some of the types defined in container-selinux.  The problem is selinux-policy never designed a nice shared library interface.

**Comment by jsegitz** [comment]
That would indicate to me that at the current state container-selinux should be a part of selinux-policy itself
